### ISSUE TITLE
Generellt intryck

### ISSUE THREAD

**Issue by mi222ep** [lw222gu/1dv450-lw222gu-API#3]
Applikationen ger ett bra generellt intryck. Koden är tydligt skriven och samtliga funktioner fungerar väl.

**Comment by mi222ep** [comment]
Bra att du separerat api'ts kod från registeringsapplikationen. Det gör det lätt att hitta rätt. Det ska jag definitivt tänka på själv.

**Comment by lw222gu** [comment]
Tack för dina kommentarer! :+1:
